### ISSUE TITLE
Waymo Open Dataset Performance on ICCV Paper

### ISSUE THREAD

**Issue by BAI-Yeqi** [tusen-ai/RangeDet#26]
Dear authors,

Many thanks for open-sourcing this great work @Abyssaledge @abbyxxn .

I have noted that there is a performance gap between the reported results on [ICCV Paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Fan_RangeDet_In_Defense_of_Range_View_for_LiDAR-Based_3D_Object_ICCV_2021_paper.pdf) and this repo's [README](https://github.com/tusen-ai/RangeDet#results-of-vehicle-evaluated-on-wod-validation-split), which are 72.85 and 70.10 L1 validation set mAP, respectively.

May I check with you what caused the difference between the paper's reported result and this repo's result?

Moreover, could you please advise how I can reproduce the paper-reported results, by modifying this repository?

Thank you!

Regards,
Charles

**Comment by Abyssaledge** [comment]
As far as I know, the 70.90 AP is the performance without data augmentation. 
In fact, I sincerely suggest that do not completely base on this repo. It is implemented with an old version MXNet (static graph), you have to build it from the source and its API has changed a lot now. And this repo heavily rely on thrid-party libraries such as horovod, open-mpi. Since some core developers (including me) have left the team, this repo might not be carefully maintained any longer. We are turely sorry for this situation. 
If you decide to use the repo, you could refer to the following issue to use data augmentations.
https://github.com/tusen-ai/RangeDet/issues/23

**Comment by BAI-Yeqi** [comment]
@Abyssaledge Alright, noted with thanks! :smiley_cat:
